#LB_DSC_19thApril_WKDY_MR_2024

Mohit Chaudhary 7011883015

Q1. Declare a float value and store it in a variable.
Check the type and print the id of the same.

In [6]:
a = 10.75       #Declaring a float value and storing it in a variable. 

print('The type of variable is:',type(a))   #Checking the type of variable.
print('The id of variable is:',id(a))       #Checking the id of variable

The type of variable is: <class 'float'>
The id of variable is: 3069576435984


Q2.  Arithmetic Operations on float
Take two different float values.
Store them in two different variables.
Do below operations on them:-
Find sum of both numbers
Find difference between them
Find the product of both numbers.
Find value after dividing first num with second number
Find the remainder after dividing first number with second number Find the quotient after dividing first number with second number Find the result of the first num to the power of the second number.

In [19]:
a1 = float(input('Enter any float value type number: '))      #Taking first value from user.
a2 = float(input('Enter another float value type number: '))  #Taking second value from user.

print('sum of first and second value is', a1 + a2)                         #Getting the sum of both values
print('Difference of first and second value is', a1 - a2)                  #Finding the differce between both values
print('Product of first and second value is', a1 * a2)                     #Finding the product of both values.
print('Division of first with second value is', a1 / a2)                   #dividing first value with second value
print('Quotient after dividing first value with second value', a1 // a2)   #Quotient after dividing first value with second value
print('Remainder after dividing first value with second value', a1 % a2)   #remainder after dividing first value with second value
print('first value to the power of second value is', a1 ** a2)             #first value to the power of second value.

Enter any float value type number:  5.5
Enter another float value type number:  2.5


sum of first and second value is 8.0
Difference of first and second value is 3.0
Product of first and second value is 13.75
Division of first with second value is 2.2
Quotient after dividing first value with second value 2.0
Remainder after dividing first value with second value 0.5
first value to the power of second value is 70.94253836732938


Q3. Comparison Operators on float
Take two different float values.
Store them in two different variables.
Do below operations on them:-
   Compare these two numbers with below operator:-
       Greater than, '>'
 Smaller than, '<'
 Greater than or equal to, '>='
 Less than or equal to, '<='
Observe their output(return type should be boolean)

In [23]:
b1 = float(input('Enter any float value type number: '))      #Taking first value from user.
b2 = float(input('Enter another float value type number: '))  #Taking second value from user.

print('Is first value Greater than second value:', b1 > b2)               #Greater than, '>'
print('Is first value Less than second value:', b1 < b2)                  #less than, '<'
print('Is first value Less than or equal to second value:', b1 <= b2)     #Greater than or equal to, '>='
print('Is first value Greater than or equal to second value', b1 >= b2)   #Less than or equal to, '<='


Enter any float value type number:  10.59
Enter another float value type number:  6.65


Is first value Greater than second value: True
Is first value Less than second value: False
Is first value Less than or equal to second value: False
Is first value Greater than or equal to second value True


As we can observe that the output we have obtained in all scenarios is Boolean (True/False), this is because comparison operator always gives us Either True or False

Q4.  Equality Operator
Take two different float values.
Store them in two different variables.
Equate them using equality operators (==, !=)
Observe the output(return type should be boolean)

In [29]:
c1 = float(input('Enter any float value type number: '))      #Taking first value from user.
c2 = float(input('Enter another float value type number: '))  #Taking second value from user.
print('Checking if values are equal using == :,', c1 == c2)        #Checking if values are equal
print('Checking if values are different using != :', c1 != c2)     #Checking if values are different

Enter any float value type number:  40.59
Enter another float value type number:  32.25


Checking if values are equal using == :, False
Checking if values are different using != : True


As we can observe that the output we have obtained in all scenarios is Boolean (True/False), this is because Equality operator always gives us Either True or False

Q5.Logical operators
Observe the output of below code
Cross check the output manually
print(10.20 and 20.30)       #both are true and second value taken >Output is 20.3
print(0.0 and 20.30)         #First is false so first value taken->Output is 0.0print(20.30 and 0.0)         #Goes to till second and second value is false so second is taken>Output is 0.0
print(0.0 and 0.0)           #First is false so first value is
taken->Output is 0.0
print(10.20 or 20.30)        #First is True so first value is
taken>Output is 10.2
print(0.0 or 20.30)          #Goes to till second and second is true second value is taken->Output is 20.3
print(20.30 or 0.0)          #First is True so first value is
taken->Output is 20.3
print(0.0 or 0.0)            #Goes to till second and second is also false and second value is taken>Output is 0.0
print(not 10.20)             #-Not of true is false->Output is False print(not 0.0)               #Not of false is True>Output is True

In [41]:
#Lets check the output manually:

print(10.20 and 20.30)       
print(0.0 and 20.30) 
print(20.30 and 0.0)
print(0.0 and 0.0)           

print(10.20 or 20.30)       
print(0.0 or 20.30)          
print(20.30 or 0.0)         
print(0.0 or 0.0)  

print(not 10.20)  
print(not 0.0)

20.3
0.0
0.0
0.0
10.2
20.3
20.3
0.0
False
True


Q6. What is the output of expression inside print statement. Cross check before running the program.
a = 10.20
b - 10.20
print(a is b)          #True or False? True 10.20<256
print(a is not b)      #True or False? False
Why the Id of float values are different when the same value is assigned to two different variables
ex: a = 10.5 b=10.5. but id will be same if I assign the variable having float i.e. a=c then both a and c's Id are same

In [6]:
#Lets check the output manually:

a = 10.20
b = 10.20

print('The id of variable a is:',id(a))
print('The id of variable b is:',id(b))

print(a is b)          
print(a is not b) 

c=a                                       #assigning the value of a to variable c
print('The id of variable c is:',id(c))

The id of variable a is: 2887129518640
The id of variable b is: 2887154937488
False
True
The id of variable c is: 2887129518640


Id of float values are different when the same value is assigned to two different variables because the memory reusibility is not applicable on float datatypes, but when only one value is stored and equality assignment (a=c) is done then both variables point to same memory address.

Q7. Bitwise operation is not applicable between instances of float. Why the Id of float values are different when the same value is assigned to two different variables
ex: a = 10.5 b=10.5. but id will be same if I assign the variable having float i.e. a=c then both a and c's Id are same
Object reusability concept is not applicable on float values.

In [69]:
x=10.25
y=13.20
print(x & y)

TypeError: unsupported operand type(s) for &: 'float' and 'float'

So we can say that the Bitwise operation is not applicable between instances of float

In [8]:
a = 10.20
b = 10.20

print('The id of variable a is:',id(a))
print('The id of variable b is:',id(b))

c=a                                       #assigning the value of a to variable c
print('The id of variable c is:',id(c))

The id of variable a is: 2887154938000
The id of variable b is: 2887154937136
The id of variable c is: 2887154938000


Id of float values are different when the same value is assigned to two different variables because the memory reusibility is not applicable on float datatypes, but when only one value is stored and equality assignment (a=c) is done then both variables point to same memory address.

Q8. Membership operation
in, not in are two membership operators and it returns boolean value
print('2.7' in 'Python2.7.8')              #True print(10.20 in [10,10.20,10+20j,'Python']) #True print(10.20 in (10,10.20,10+20j,'Python')) # True print(20.30 in {1,20.30,30+40j})           # True print(2.3 in {1:100, 2.3:200, 30+40j:300}) # True print(10 in range(20))                     # True

In [15]:
#Lets check the output manually:

print('2.7' in 'Python2.7.8')
print(10.20 in [10,10.20,10+20j,'Python']) 
print(10.20 in (10,10.20,10+20j,'Python')) 
print(20.30 in {1,20.30,30+40j})           
print(2.3 in {1:100, 2.3:200, 30+40j:300}) 
print(10 in range(20))                     

True
True
True
True
True
True
